-- ISTesport Telegram Bot Stage 4
-- Match announcements, reminders, LIVE state and results.

create table if not exists public.telegram_match_publications (
  id bigint generated by default as identity primary key,
  match_id text not null,
  event_type text not null
    check (event_type in ('announcement', 'reminder', 'live', 'result')),
  status text not null
    check (status in ('baseline', 'processing', 'sent', 'failed', 'skipped')),
  telegram_chat_id text null,
  telegram_message_id bigint null,
  attempt_count integer not null default 0,
  last_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, event_type)
);

create index if not exists telegram_match_publications_status_idx
  on public.telegram_match_publications (status, updated_at desc);

create index if not exists telegram_match_publications_match_idx
  on public.telegram_match_publications (match_id);

alter table public.telegram_match_publications enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Only the Railway Telegram worker uses this table through service_role.

comment on table public.telegram_match_publications is
  'Idempotency and delivery state for ISTesport Telegram match notifications';
