-- ISTesport Telegram Bot Stage 11
-- Telegram discussion-group moderation.

create table if not exists public.telegram_moderation_settings (
  chat_id bigint primary key,
  anti_spam boolean not null default true,
  link_filter boolean not null default false,
  flood_limit integer not null default 6
    check (flood_limit between 3 and 50),
  flood_window_seconds integer not null default 10
    check (flood_window_seconds between 3 and 300),
  duplicate_limit integer not null default 3
    check (duplicate_limit between 2 and 20),
  duplicate_window_seconds integer not null default 60
    check (duplicate_window_seconds between 10 and 3600),
  warn_limit integer not null default 3
    check (warn_limit between 1 and 20),
  auto_mute_minutes integer not null default 10
    check (auto_mute_minutes between 1 and 43200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_moderation_warnings (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  user_id bigint not null,
  username text null,
  display_name text not null,
  moderator_id bigint null,
  reason text null,
  automatic boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  cleared_at timestamptz null,
  cleared_by bigint null
);

create index if not exists telegram_moderation_warnings_active_idx
  on public.telegram_moderation_warnings (
    chat_id,
    user_id,
    active,
    created_at desc
  );

create table if not exists public.telegram_moderation_filters (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  phrase text not null,
  created_by bigint not null,
  created_at timestamptz not null default now(),
  check (char_length(phrase) between 1 and 120)
);

create unique index if not exists telegram_moderation_filters_unique_idx
  on public.telegram_moderation_filters (
    chat_id,
    lower(phrase)
  );

create index if not exists telegram_moderation_filters_chat_idx
  on public.telegram_moderation_filters (chat_id, phrase);

create table if not exists public.telegram_moderation_events (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  action text not null,
  target_user_id bigint null,
  actor_user_id bigint null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists telegram_moderation_events_chat_idx
  on public.telegram_moderation_events (
    chat_id,
    created_at desc
  );

alter table public.telegram_moderation_settings enable row level security;
alter table public.telegram_moderation_warnings enable row level security;
alter table public.telegram_moderation_filters enable row level security;
alter table public.telegram_moderation_events enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Railway accesses these tables only through SUPABASE_SERVICE_ROLE_KEY.

comment on table public.telegram_moderation_settings is
  'Per-group ISTesport Telegram moderation configuration';

comment on table public.telegram_moderation_warnings is
  'Persistent active and historical Telegram group warnings';

comment on table public.telegram_moderation_filters is
  'Per-group blocked phrases used by ISTesport Telegram moderation';

comment on table public.telegram_moderation_events is
  'Audit history of manual and automatic Telegram moderation actions';
