-- ISTesport Telegram Bot Stage 5
-- FACEIT statistics and automatic roster change notifications.

create table if not exists public.telegram_roster_publications (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  status text not null
    check (status in ('processing', 'sent', 'failed')),
  change_summary jsonb not null default '{}'::jsonb,
  telegram_chat_id text null,
  telegram_message_id bigint null,
  attempt_count integer not null default 0,
  last_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_roster_publications_status_idx
  on public.telegram_roster_publications (status, updated_at desc);

alter table public.telegram_roster_publications enable row level security;

-- No public RLS policies are added.
-- The Railway worker accesses this table with service_role only.

comment on table public.telegram_roster_publications is
  'Idempotency and delivery state for ISTesport Telegram roster change notifications';
