-- ISTesport Telegram Bot Stage 9
-- Manual channel posts and admin channel management.

create table if not exists public.telegram_manual_posts (
  id bigint generated by default as identity primary key,
  status text not null default 'published'
    check (status in ('published', 'deleted')),
  text text not null,
  image_url text null,
  button_text text null,
  button_url text null,
  telegram_chat_id text not null,
  telegram_message_id bigint not null,
  created_by bigint not null,
  published_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_manual_posts_status_created_idx
  on public.telegram_manual_posts (status, created_at desc);

create table if not exists public.telegram_manual_post_drafts (
  telegram_user_id bigint primary key,
  mode text not null check (mode in ('create', 'edit')),
  step text not null,
  data jsonb not null default '{}'::jsonb,
  language text not null default 'uk'
    check (language in ('uk', 'ru', 'en')),
  target_post_id bigint null
    references public.telegram_manual_posts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

alter table public.telegram_manual_posts enable row level security;
alter table public.telegram_manual_post_drafts enable row level security;

-- No anon/authenticated policies are created.
-- Railway uses SUPABASE_SERVICE_ROLE_KEY only.

comment on table public.telegram_manual_posts is
  'Manual channel posts created and managed through ISTesport Telegram Bot';

comment on table public.telegram_manual_post_drafts is
  'Persistent drafts for manual channel post create/edit workflows';
