-- ISTesport Telegram Bot Stage 3
-- Automatic publication of future published website news into Telegram.

create table if not exists public.telegram_bot_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_news_publications (
  id bigint generated by default as identity primary key,
  news_post_id text not null unique,
  status text not null
    check (status in ('baseline', 'processing', 'sent', 'failed')),
  telegram_chat_id text null,
  telegram_message_id bigint null,
  attempt_count integer not null default 0,
  last_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_news_publications_status_idx
  on public.telegram_news_publications (status, updated_at desc);

alter table public.telegram_bot_state enable row level security;
alter table public.telegram_news_publications enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Only the Railway Telegram worker uses these tables through service_role.

comment on table public.telegram_bot_state is
  'Persistent internal state for ISTesport Telegram Bot workers';

comment on table public.telegram_news_publications is
  'Idempotency and delivery state for website news published to Telegram';
