-- ISTesport Telegram Bot Stage 7
-- Recruitment, support and partnership requests.

create table if not exists public.telegram_requests (
  id bigint generated by default as identity primary key,
  type text not null
    check (type in ('recruitment', 'support', 'partnership')),
  status text not null default 'new'
    check (status in ('new', 'in_progress', 'approved', 'rejected', 'closed')),
  telegram_user_id bigint not null,
  username text null,
  display_name text not null,
  language text not null default 'uk'
    check (language in ('uk', 'ru', 'en')),
  payload jsonb not null default '{}'::jsonb,
  assigned_to bigint null,
  admin_note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz null
);

create index if not exists telegram_requests_user_idx
  on public.telegram_requests (telegram_user_id, created_at desc);

create index if not exists telegram_requests_status_idx
  on public.telegram_requests (status, created_at desc);

create table if not exists public.telegram_request_drafts (
  telegram_user_id bigint primary key,
  request_type text not null
    check (request_type in ('recruitment', 'support', 'partnership')),
  step integer not null default 0 check (step >= 0),
  answers jsonb not null default '{}'::jsonb,
  language text not null default 'uk'
    check (language in ('uk', 'ru', 'en')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create table if not exists public.telegram_request_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null
    references public.telegram_requests(id) on delete cascade,
  actor_telegram_user_id bigint null,
  action text not null,
  from_status text null,
  to_status text null,
  note text null,
  created_at timestamptz not null default now()
);

create index if not exists telegram_request_events_request_idx
  on public.telegram_request_events (request_id, created_at asc);

alter table public.telegram_requests enable row level security;
alter table public.telegram_request_drafts enable row level security;
alter table public.telegram_request_events enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Railway uses SUPABASE_SERVICE_ROLE_KEY.

comment on table public.telegram_requests is
  'Recruitment, support and partnership requests created through ISTesport Telegram Bot';

comment on table public.telegram_request_drafts is
  'Persistent 24-hour form drafts for ISTesport Telegram Bot requests';

comment on table public.telegram_request_events is
  'Audit history for ISTesport Telegram Bot request status changes';
