-- ISTesport Telegram Bot Stage 8
-- Giveaways and Telegram polls.

create table if not exists public.telegram_giveaways (
  id bigint generated by default as identity primary key,
  title text not null,
  prize text not null,
  rules text null,
  status text not null default 'publishing'
    check (status in (
      'publishing',
      'active',
      'drawing',
      'finished',
      'cancelled',
      'failed'
    )),
  created_by bigint not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  ended_at timestamptz null,
  telegram_chat_id text null,
  telegram_message_id bigint null,
  participant_count integer not null default 0,
  winner_telegram_user_id bigint null,
  winner_username text null,
  winner_display_name text null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_giveaways_status_ends_idx
  on public.telegram_giveaways (status, ends_at asc);

create table if not exists public.telegram_giveaway_participants (
  id bigint generated by default as identity primary key,
  giveaway_id bigint not null
    references public.telegram_giveaways(id) on delete cascade,
  telegram_user_id bigint not null,
  username text null,
  display_name text not null,
  joined_at timestamptz not null default now(),
  unique (giveaway_id, telegram_user_id)
);

create index if not exists telegram_giveaway_participants_giveaway_idx
  on public.telegram_giveaway_participants (giveaway_id, id asc);

create table if not exists public.telegram_giveaway_drafts (
  telegram_user_id bigint primary key,
  step text not null,
  data jsonb not null default '{}'::jsonb,
  language text not null default 'uk'
    check (language in ('uk', 'ru', 'en')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create table if not exists public.telegram_polls (
  id bigint generated by default as identity primary key,
  telegram_poll_id text not null unique,
  telegram_chat_id text not null,
  telegram_message_id bigint not null,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  is_anonymous boolean not null default true,
  status text not null default 'open'
    check (status in ('open', 'closed')),
  created_by bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz null
);

create index if not exists telegram_polls_status_created_idx
  on public.telegram_polls (status, created_at desc);

create table if not exists public.telegram_poll_drafts (
  telegram_user_id bigint primary key,
  step text not null,
  data jsonb not null default '{}'::jsonb,
  language text not null default 'uk'
    check (language in ('uk', 'ru', 'en')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

alter table public.telegram_giveaways enable row level security;
alter table public.telegram_giveaway_participants enable row level security;
alter table public.telegram_giveaway_drafts enable row level security;
alter table public.telegram_polls enable row level security;
alter table public.telegram_poll_drafts enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Railway accesses these tables through SUPABASE_SERVICE_ROLE_KEY only.

comment on table public.telegram_giveaways is
  'ISTesport Telegram giveaway lifecycle and winner state';

comment on table public.telegram_giveaway_participants is
  'Unique participant entries for ISTesport Telegram giveaways';

comment on table public.telegram_polls is
  'Telegram native polls published by ISTesport Bot';
