begin;

alter table public.discord_guilds
  add column if not exists recruitment_channel_id text,
  add column if not exists recruitment_review_channel_id text,
  add column if not exists recruitment_member_role_id text;

create table if not exists public.discord_recruitment_applications (
  id bigint generated by default as identity primary key,
  guild_id text not null references public.discord_guilds(guild_id) on delete cascade,
  discord_user_id text not null,
  discord_username text not null default '',
  category text not null check (
    category in ('player','coach','management','content','design','moderation','other')
  ),
  status text not null default 'submitted' check (
    status in ('submitted','interview','accepted','rejected','withdrawn')
  ),
  answers jsonb not null default '{}'::jsonb,
  review_channel_id text,
  review_message_id text,
  reviewer_id text,
  reviewer_username text,
  review_note text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists discord_recruitment_active_unique_idx
  on public.discord_recruitment_applications (guild_id, discord_user_id, category)
  where status in ('submitted', 'interview');

create index if not exists discord_recruitment_guild_status_created_idx
  on public.discord_recruitment_applications (guild_id, status, created_at desc);

create index if not exists discord_recruitment_user_created_idx
  on public.discord_recruitment_applications (discord_user_id, created_at desc);

alter table public.discord_recruitment_applications enable row level security;

revoke all on table public.discord_recruitment_applications from anon, authenticated;

commit;
