-- ISTesport Telegram Bot Stage 6
-- Twitch LIVE notifications.

create table if not exists public.telegram_live_publications (
  id bigint generated by default as identity primary key,
  platform text not null
    check (platform in ('twitch')),
  stream_id text not null,
  status text not null
    check (status in ('processing', 'sent', 'failed')),
  telegram_chat_id text null,
  telegram_message_id bigint null,
  attempt_count integer not null default 0,
  last_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (platform, stream_id)
);

create index if not exists telegram_live_publications_status_idx
  on public.telegram_live_publications (platform, status, updated_at desc);

alter table public.telegram_live_publications enable row level security;

-- No public policies. Railway uses the service_role key only.

comment on table public.telegram_live_publications is
  'Idempotency and delivery state for ISTesport Twitch LIVE Telegram notifications';
