-- ISTesport Telegram Bot Stage 2
-- Base users, roles, language preferences and audit log.

create table if not exists public.telegram_bot_users (
  telegram_user_id bigint primary key,
  username text null,
  display_name text null,
  role text not null default 'user'
    check (role in ('user', 'editor', 'moderator', 'admin', 'owner')),
  language text not null default 'uk'
    check (language in ('uk', 'ru', 'en')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_bot_users_role_idx
  on public.telegram_bot_users (role);

create table if not exists public.telegram_bot_audit_log (
  id bigint generated by default as identity primary key,
  actor_telegram_user_id bigint null,
  action text not null,
  target_type text null,
  target_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists telegram_bot_audit_actor_idx
  on public.telegram_bot_audit_log (actor_telegram_user_id, created_at desc);

create index if not exists telegram_bot_audit_action_idx
  on public.telegram_bot_audit_log (action, created_at desc);

alter table public.telegram_bot_users enable row level security;
alter table public.telegram_bot_audit_log enable row level security;

-- No public policies are created intentionally.
-- The Telegram worker accesses these tables only with SUPABASE_SERVICE_ROLE_KEY.
-- The service role bypasses RLS. Browser/anon clients receive no access.

comment on table public.telegram_bot_users is
  'ISTesport Telegram Bot user role and language registry';

comment on table public.telegram_bot_audit_log is
  'ISTesport Telegram Bot privileged action audit log';
