-- ISTesport Telegram Bot Stage 12
-- Observability, health history, error journal, security diagnostics.

create table if not exists public.telegram_bot_health_snapshots (
  id bigint generated by default as identity primary key,
  ok boolean not null,
  checks jsonb not null default '{}'::jsonb,
  uptime_seconds bigint not null default 0
    check (uptime_seconds >= 0),
  created_at timestamptz not null default now()
);

create index if not exists telegram_bot_health_snapshots_created_idx
  on public.telegram_bot_health_snapshots (created_at desc);

create index if not exists telegram_bot_health_snapshots_ok_idx
  on public.telegram_bot_health_snapshots (ok, created_at desc);

create table if not exists public.telegram_bot_error_log (
  id bigint generated by default as identity primary key,
  scope text not null,
  message text not null,
  error_name text null,
  error_code text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (char_length(scope) between 1 and 200),
  check (char_length(message) between 1 and 2000)
);

create index if not exists telegram_bot_error_log_created_idx
  on public.telegram_bot_error_log (created_at desc);

create index if not exists telegram_bot_error_log_scope_idx
  on public.telegram_bot_error_log (scope, created_at desc);

alter table public.telegram_bot_health_snapshots enable row level security;
alter table public.telegram_bot_error_log enable row level security;

-- No anon/authenticated policies are intentionally created.
-- Railway uses SUPABASE_SERVICE_ROLE_KEY.

comment on table public.telegram_bot_health_snapshots is
  'Periodic and manual health snapshots for ISTesport Telegram Bot';

comment on table public.telegram_bot_error_log is
  'Persistent operational error journal for ISTesport Telegram Bot';
