begin;

create table if not exists public.discord_guilds (
  guild_id text primary key,
  guild_name text not null default '',
  guild_icon text,
  bot_user_id text,
  active boolean not null default true,
  member_count integer,
  locale text not null default 'uk',
  command_channel_id text,
  news_channel_id text,
  log_channel_id text,
  welcome_channel_id text,
  config jsonb not null default '{}'::jsonb,
  installed_at timestamptz not null default now(),
  removed_at timestamptz,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discord_bot_audit (
  id bigint generated by default as identity primary key,
  guild_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists discord_guilds_active_idx
  on public.discord_guilds (active, updated_at desc);

create index if not exists discord_bot_audit_guild_created_idx
  on public.discord_bot_audit (guild_id, created_at desc);

alter table public.discord_guilds enable row level security;
alter table public.discord_bot_audit enable row level security;

revoke all on table public.discord_guilds from anon, authenticated;
revoke all on table public.discord_bot_audit from anon, authenticated;

commit;
