-- ISTe Wear secure shop foundation
-- Run this file once in Supabase -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.shop_products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  collection text not null default 'DROP 001 // CORE',
  short_description text not null default '',
  description text not null default '',
  price_uah integer null check (price_uah is null or price_uah between 0 and 1000000),
  status text not null default 'draft' check (status in ('draft', 'live', 'soldout', 'hidden')),
  image_url text null,
  visual_variant text not null default 'tee' check (visual_variant in ('tee', 'hoodie', 'jersey')),
  sizes text[] not null default array['S','M','L','XL']::text[],
  sort_order integer not null default 0 check (sort_order between -1000 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_preorders (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.shop_products(id) on delete restrict,
  name text not null check (char_length(name) between 2 and 60),
  email text not null check (char_length(email) between 3 and 254),
  size text not null check (char_length(size) between 1 and 8),
  quantity integer not null check (quantity between 1 and 3),
  locale text not null default 'ru' check (locale in ('uk', 'ru', 'en')),
  consent_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.shop_admin_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  product_id uuid null references public.shop_products(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.shop_rate_limits (
  rate_key text not null,
  bucket_start timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  updated_at timestamptz not null default now(),
  primary key (rate_key, bucket_start)
);

create index if not exists shop_products_public_order_idx
  on public.shop_products (status, sort_order, created_at);

create index if not exists shop_preorders_created_at_idx
  on public.shop_preorders (created_at desc);

create index if not exists shop_preorders_product_created_idx
  on public.shop_preorders (product_id, created_at desc);

create index if not exists shop_preorders_email_created_idx
  on public.shop_preorders (lower(email), created_at desc);

create index if not exists shop_rate_limits_updated_at_idx
  on public.shop_rate_limits (updated_at);

create index if not exists shop_admin_audit_created_at_idx
  on public.shop_admin_audit (created_at desc);

create or replace function public.iste_shop_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists shop_products_touch_updated_at on public.shop_products;

create trigger shop_products_touch_updated_at
before update on public.shop_products
for each row
execute function public.iste_shop_touch_updated_at();

create or replace function public.shop_consume_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_window integer := greatest(60, least(coalesce(p_window_seconds, 3600), 86400));
  v_limit integer := greatest(1, least(coalesce(p_limit, 5), 100));
  v_bucket timestamptz;
  v_count integer;
begin
  if p_key is null or char_length(p_key) < 32 or char_length(p_key) > 128 then
    return false;
  end if;

  v_bucket := to_timestamp(
    floor(extract(epoch from v_now) / v_window) * v_window
  );

  insert into public.shop_rate_limits (
    rate_key,
    bucket_start,
    request_count,
    updated_at
  ) values (
    p_key,
    v_bucket,
    1,
    v_now
  )
  on conflict (rate_key, bucket_start)
  do update set
    request_count = public.shop_rate_limits.request_count + 1,
    updated_at = excluded.updated_at
  returning request_count into v_count;

  return v_count <= v_limit;
end;
$$;

-- The browser receives no direct table access. All shop traffic goes through /api/shop.
alter table public.shop_products enable row level security;
alter table public.shop_preorders enable row level security;
alter table public.shop_rate_limits enable row level security;
alter table public.shop_admin_audit enable row level security;

revoke all on table public.shop_products from anon, authenticated;
revoke all on table public.shop_preorders from anon, authenticated;
revoke all on table public.shop_rate_limits from anon, authenticated;
revoke all on table public.shop_admin_audit from anon, authenticated;

revoke all on function public.shop_consume_rate_limit(text, integer, integer) from public;
revoke all on function public.shop_consume_rate_limit(text, integer, integer) from anon, authenticated;
grant execute on function public.shop_consume_rate_limit(text, integer, integer) to service_role;

-- Seed the first visual drop. Prices intentionally stay NULL until you decide them.
insert into public.shop_products (
  slug,
  name,
  collection,
  short_description,
  description,
  price_uah,
  status,
  visual_variant,
  sizes,
  sort_order
)
values
  (
    'iste-core-tee',
    'ISTe CORE TEE',
    'DROP 001 // CORE',
    'Плотная oversize футболка в чёрно-красной эстетике ISTe.',
    'Первый базовый силуэт ISTe Wear. Минималистичный фронт, выраженная спина и акцент на фирменной красной линии.',
    null,
    'live',
    'tee',
    array['S','M','L','XL','XXL']::text[],
    10
  ),
  (
    'iste-core-hoodie',
    'ISTe CORE HOODIE',
    'DROP 001 // CORE',
    'Тяжёлый худи с минимальным фронтом и агрессивной спиной.',
    'Чёрная база, красные акценты и визуальный язык команды без ощущения обычного сувенирного мерча.',
    null,
    'live',
    'hoodie',
    array['S','M','L','XL','XXL']::text[],
    20
  ),
  (
    'iste-pro-jersey',
    'ISTe PRO JERSEY',
    'DROP 001 // CORE',
    'Игровая джерси команды ISTe для матчей, контента и сообщества.',
    'Форма в фирменной чёрно-красно-белой палитре ISTe. Первая версия доступна как заявка на предзаказ.',
    null,
    'live',
    'jersey',
    array['S','M','L','XL','XXL']::text[],
    30
  )
on conflict (slug) do update set
  name = excluded.name,
  collection = excluded.collection,
  short_description = excluded.short_description,
  description = excluded.description,
  visual_variant = excluded.visual_variant,
  sizes = excluded.sizes,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Optional cleanup command. Run occasionally or schedule it in Supabase Cron later.
-- delete from public.shop_rate_limits where updated_at < now() - interval '7 days';
